### ISSUE TITLE
Invalid sudoku

### ISSUE THREAD

**Issue by JesperVa** [kaajjo/LibreSudoku#76]
I generated a moderate 9x9. Only remaining value for middle block is 2, but is blocked by a generated 2 even though I am at 0 mistakes.

![Screenshot_20231007_155419_LibreSudoku.jpg](https://github.com/kaajjo/Libre-Sudoku/assets/17760977/c47ed14b-683a-423d-977e-1a1d50d36092)

Putting in the sudoku in a sudokusolver generates at least 10 valid solutions, which invalidates proper sudoku regimes.

**Comment by Riksu9000** [comment]
Hi. Sorry, but it seems to me that the puzzle is valid. Do you happen to have mistakes checking set to rules violations, which doesn't catch all mistakes immediately?

![Screenshot 2024-08-16 at 11-13-24 Sudoku Solver - Solve your sudoku step by step](https://github.com/user-attachments/assets/89e9ac16-aa56-400a-b5e1-fcb19e14a52c)

**Comment by kaajjo** [comment]
Check `mistakes checking` setting. The default is rule violations, you can choose to check values with solution. This puzzle has one unique solution, so it's valid, you just made a mistake somewhere
