### ISSUE TITLE
Generating invalid layouts

### ISSUE THREAD

**Issue by Stenters** [kaajjo/LibreSudoku#83]
The app can generate unsolvable layouts. See examples:

![Screenshot_20240104_133718_LibreSudoku](https://github.com/kaajjo/Libre-Sudoku/assets/34109965/1708a386-e045-4680-89f4-7ea10e2d38f0)
![Screenshot_20240105_085130_LibreSudoku](https://github.com/kaajjo/Libre-Sudoku/assets/34109965/0b1036b7-f488-405a-bfa5-fd365023fb68)

**Comment by kaajjo** [comment]
Layouts are ok, all generated puzzles are tested to have only one possible solution
The second one for example has unique solution
`800900003001004000090521000900000006020005000005143000108200000430006020060000010`
<img src="https://github.com/user-attachments/assets/8facb4bc-6a61-4835-99c3-2eee4c36a6f3" width=75%>

You can test [here](https://www.thonky.com/sudoku/solution-count)  and [here](https://qqwing.com/solve.html)
